### ISSUE TITLE
Android 13, videos playing in the webview freezes but audio continues. Not happening on older versions of android.

### ISSUE THREAD

**Issue by sandy428** [react-native-webview/react-native-webview#2693] opened 2022-09-30 21:50 UTC
**Bug description:**

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS:
 - OS version:
 - react-native version:
 - react-native-webview version:

**Comment by TheAlmightyBob** [comment] 2022-09-30 22:03
Duplicate of #2694

**Closed by TheAlmightyBob** 2022-09-30 22:03 UTC
Labels: Type: bug report
