### ISSUE TITLE
Execution failed for task ':react-native-webview:compileDebugKotlin'

### ISSUE THREAD

**Issue by riooastfu** [react-native-webview/react-native-webview#2579] opened 2022-07-04 04:41 UTC
I have installed react-native-webview with the following instruction, but after installation i got problems when i want execute "npm run android". Someone please help me solve this :(

**Comment by ajaxjiang96** [comment] 2022-07-04 06:10
I got the same issue after upgraded to React Native 0.69. Looks like it's caused by mismatch of kotlin versions. My temporary workaround is to manually overrite the kotlin version for react-native-webview and persist it with patch-package.
Here is my patch for version `11.22.2`.
```patch
diff --git a/node_modules/react-native-webview/android/gradle.properties b/node_modules/react-native-webview/android/gradle.properties
index a3b48de..23db9cc 100644
--- a/node_modules/react-native-webview/android/gradle.properties
+++ b/node_modules/react-native-webview/android/gradle.properties
@@ -1,4 +1,4 @@
-ReactNativeWebView_kotlinVersion=1.3.50
+ReactNativeWebView_kotlinVersion=1.6.10
 ReactNativeWebView_webkitVersion=1.4.0
 ReactNativeWebView_compileSdkVersion=29
 ReactNativeWebView_buildToolsVersion=29.0.3
```

**Comment by ajaxjiang96** [comment] 2022-07-04 06:12
duplicate of #2578

**Comment by Bilal-Abdeen** [comment] 2022-07-05 07:33
The solution in [#2568](https://github.com/react-native-webview/react-native-webview/issues/2568#issuecomment-1172557823) worked for me.

**Closed** 2022-07-05 10:24 UTC

**Comment by Biplovkumar** [comment] 2022-11-07 11:04
add this in to /android/build.gradle

```
def REACT_NATIVE_VERSION = new File(['node', '--print',"JSON.parse(require('fs').readFileSync(require.resolve('react-native/package.json'), 'utf-8')).version"].execute(null, rootDir).text.trim())

allprojects {

//...


configurations.all {
    resolutionStrategy {
        // Remove this override in 0.65+, as a proper fix is included in react-native itself.
        force "com.facebook.react:react-native:" + REACT_NATIVE_VERSION
    }
    }

}
```

**Comment by Gentlekboy** [comment] 2022-11-15 11:17
I tried @Biplovkumar's solution.
It worked for me.
Thanks, @Biplovkumar!!
