### ISSUE TITLE
Package react-native-webview has been ignored because it contains invalid configuration

### ISSUE THREAD

**Issue by gonglixin980926** [react-native-webview/react-native-webview#2430] opened 2022-03-31 12:39 UTC
**Bug description:**

I am trying to use react-native-webview and following step. But it doesn't work.

yarn add react-native-webview
cd ios && pod install && cd .. # CocoaPods on iOS needs this extra step

There is problem.
![image](https://user-images.githubusercontent.com/40887236/161056468-9460e0fd-3d44-4788-8c8b-7141f0df4be5.png)

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS: macOS
 - OS version: 12.3
 - react-native version: 0.67.4
 - react-native-webview version: 11.18.0

**Comment by nitrique** [comment] 2022-03-31 13:11
BTW duplicate of issue [2426](https://github.com/react-native-webview/react-native-webview/issues/2426)

**Comment by MidKnightXI** [comment] 2022-03-31 13:45
same problem for me on macOS 
```js
arn run v1.22.17
$ react-native run-android
warn Package react-native-webview has been ignored because it contains invalid configuration. Reason: Cannot find module 'react-native-test-app/package.json'
Require stack:
- /Users/midknight/epitech/area/mobile-app/node_modules/react-native-webview/react-native.config.js
- /Users/midknight/epitech/area/mobile-app/node_modules/cosmiconfig/node_modules/import-fresh/index.js
- /Users/midknight/epitech/area/mobile-app/node_modules/cosmiconfig/dist/loaders.js
- /Users/midknight/epitech/area/mobile-app/node_modules/cosmiconfig/dist/createExplorer.js
- /Users/midknight/epitech/area/mobile-app/node_modules/cosmiconfig/dist/index.js
- /Users/midknight/epitech/area/mobile-app/node_modules/@react-native-community/cli/build/tools/config/readConfigFromDisk.js
- /Users/midknight/epitech/area/mobile-app/node_modules/@react-native-community/cli/build/tools/config/index.js
- /Users/midknight/epitech/area/mobile-app/node_modules/@react-native-community/cli/build/commands/install/install.js
- /Users/midknight/epitech/area/mobile-app/node_modules/@react-native-community/cli/build/commands/index.js
- /Users/midknight/epitech/area/mobile-app/node_modules/@react-native-community/cli/build/index.js
- /Users/midknight/epitech/area/mobile-app/node_modules/react-native/cli.js
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1017 file(s) to forward-jetify. Using 10 workers...
info JS server already running.
info Installing the app...
```

**Comment by gonglixin980926** [comment] 2022-04-01 02:45
> is it the same as #2421 ?

yes

**Comment by MidKnightXI** [comment] 2022-04-01 09:26
To temporarly fix it, replace in your `package.json` this line `"react-native-webview": "^11.18.0"` by `"react-native-webview": "11.17.2"`

**Closed** 2022-04-01 17:17 UTC
Labels: Type: bug report

**Comment by loneverse** [comment] 2023-01-23 09:25
This error message typically occurs when the "react-native-webview" package is not properly configured in your project. To fix this issue, you can try the following steps:

Make sure that you have installed the "react-native-webview" package using npm or yarn.

Check that the package is correctly imported in your project.

If you are using a version of React Native that is less than 0.60, you need to link the "react-native-webview" package. You can do this by running the command "react-native link react-native-webview" in your project's root directory.

If you are using a version of React Native that is greater than or equal to 0.60, linking is not necessary. So, you can make sure that you are using the latest version of react-native-webview.

If none of these steps work, you can try uninstalling and reinstalling the package, or you can check if there are any other dependencies causing conflicts.

Make sure that you are using the latest version of React Native.

If none of the above steps work, please share the version of react-native and react-native-webview you are using.

Support my blog: https://Nairobinewsnow.com
