### ISSUE TITLE
Windows App certification kit report an error for React-native-webview packages

### ISSUE THREAD

**Issue by kibrahim738** [react-native-webview/react-native-webview#2555] opened 2022-06-22 14:08 UTC
**Bug description:**

I try to build a react native app for the Windows UWP app. After building the app when I run the app with the windows app certification kit, it reports an error (supported API error for Microsoft webview2).  I tried several solutions (ex: downgrading Microsoft webview2 to 2.7.1 & 2.7.0, using different windows 11 sdk 22000 and so on), but can not fix the problem. Without passing the windows app certification, I can not submit the app in windows app store.
 

**To Reproduce:**

- git clone https://github.com/hrdipto/react-native-app
- cd react-native-app
- yarn install
- npx react-native-windows-init --overwrite
- load the windows/temp.sln file in visual studio
- double click on temp/Package.appxmanifest and edit it [help](https://docs.google.com/document/d/1sUwpDg8ZXqxuvHF1FAZLBU_xu16zjM6ihB7e15NosPc)
- right-click on temp folder > publish > create app packages
- after creating the package windows app certification kit open to testing your app
- in the error report you will see the error

**Expected behavior:**

The UWP app should pass windows app certification kit.

**Screenshots/Videos:**

- This error occurred when I build the app with the visual studio default configuration. [Click Here](https://drive.google.com/file/d/1HAPucZzNvkUi3M6eJ5tozb6ErZWJino2/view?usp=sharing) to see the error.
- This error occurred when I upgrade windows 11 sdk 22000. [click here](https://drive.google.com/file/d/1tHqly6Nz9gUrrtGtz9_JKJArEcxip7Jb/view?usp=sharing) to see the error.

**Environment:**
 - OS: Windows 10
 - OS version: 10
 - react-native version: 0.68.2
 - react-native-webview version: ^11.22.3
 - windows 11 sdk 22000
 - windows 10 sdk

**Comment by asklar** [comment] 2022-06-23 18:23
Duplicate of #2553

**Closed by asklar** 2022-06-23 18:23 UTC
Labels: Type: bug report
