### ISSUE TITLE
🟥 BUG NEED HELP -------- > IOS Crashed when using webview and Modal

### ISSUE THREAD

**Issue by Martin2037** [react-native-webview/react-native-webview#3345] opened 2024-03-02 10:41 UTC
**Bug description:**
react-native-webview + modal = crash
example: 
1. react-native-webview + web3Modal
2. react-native-webview + react-native-actions-sheet

**To Reproduce:**
https://github.com/Martin2037/rn-modal-crash

**Expected behavior:**
Do not crash

**Screenshots/Videos:**
![e74b3cd0-1ed8-4153-9714-359fa0dead23](https://github.com/react-native-webview/react-native-webview/assets/63692237/be6e1b69-45db-4908-8201-41f186ffccc2)
**Environment:**
 - OS: MACOS M1
 - OS version: 
 - react-native version: 0.73.5
 - react-native-webview version: 13.8.1
 - new arch (fabric + turbo + codegen)
 - Iphone 15 pro

**Just run the following commands to reproduce this weird bug.👇
cd ios
RCT_NEW_ARCH_ENABLED=1 bundle exec pod install**

After that, start up the project again. It'll compile just fine, no errors. But as soon as you click the button to open the modal, bam! The whole thing crashes.

**Comment by Martin2037** [comment] 2024-03-03 08:31
update:
I think the **supportedOrientations** is the main reason?

**Comment by Nalymoslih** [comment] 2024-03-03 13:55
Any update ?

**Comment by Martin2037** [comment] 2024-03-03 14:17
> Any update ? 任何更新 ？

No updates yet, bro... I've been actively looking for a solution.
I've checked all the source code about modal in webview, but I think the code is fine, so I'm guessing it's a problem with react-native?.....

**Comment by Martin2037** [comment] 2024-03-04 12:51
@Titozzz

**Comment by hramos** [comment] 2024-03-05 22:35
The sample repo that you provided does not use `react-native-webview` at all, other than declaring it as a node dependency.

**Comment by Martin2037** [comment] 2024-03-06 02:30
> The sample repo that you provided does not use `react-native-webview` at all, other than declaring it as a node dependency.

This is the weirdest thing - as soon as I install react-native-webview and open a modal, it crashed. And get this, I haven't even declared a webview in my code!

**Comment by hramos** [comment] 2024-03-06 16:34
Since it is not being used, it's unlikely that RNW itself is the culprit, but rather might be an issue in a particular version of some other common dependency between RNW and another of your installed packages.

Compare your yarn.lock or package-lock.json before and after installing `react-native-webview`, and see which other dependencies are being pulled in. That may give you a clue as to which package might be leading to your troubles with the modal.

**Comment by ignaciosantise** [comment] 2024-03-11 18:28
Hi @hramos thanks for the insight!

Im using yarn, and there's no big differences in the dependencies after installing `react-native-webview`:

1. `escape-string-regexp@2.0.0`
<img width="1494" alt="Screenshot 2024-03-11 at 15 26 28" src="https://github.com/react-native-webview/react-native-webview/assets/25931366/ce4d9efb-f700-41e0-9765-749ecfd33414">

2. `invariant@2.2.4`
<img width="1253" alt="Screenshot 2024-03-11 at 15 26 33" src="https://github.com/react-native-webview/react-native-webview/assets/25931366/5cfd259d-6450-4b85-9ca4-7c87729b9372">

3. `react-native-webview`
<img width="1332" alt="Screenshot 2024-03-11 at 15 26 40" src="https://github.com/react-native-webview/react-native-webview/assets/25931366/7a3889b2-d487-4953-b7fa-8d47d47bfd9f">


Those are all the differences before - after installing 🤔

**Comment by netmaxt3r** [comment] 2024-04-04 20:06
root cause of this issue is a bug in codegen in new architecture for more details see [rn-issue](https://github.com/facebook/react-native/issues/43821). for now only hope for you is disable new architecture . 

@titozzz @jamonholmgren
this is not a react-native-webview bug,  can we close this citing the upstream issue

**Closed** 2024-04-04 20:26 UTC
Labels: Type: bug report
